### ISSUE TITLE
Full example project

### ISSUE THREAD

**Issue by radar** [bitwalker/exirc#38]
I'm new to Elixir and I'm trying out exirc. Here's my repo: https://github.com/radar/railsbot.ex.

When I run `mix run` to start the bot, it connects to the server and then quits instantly.

I would like to see a full example application to know where I am going wrong. Do you have one available?

**Comment by mrlamroger** [comment]
+1

**Comment by bitwalker** [comment]
Sure I can throw something together

**Comment by bitwalker** [comment]
@radar @mrlamroger There was already an example under `examples`, but I've written another one from scratch which acts as a basic IRC bot. It will respond if it is mentioned along with the word "hi", as in "hi exirc-example", or if it is private messaged. Anything above and beyond that is left as an exercise for the reader. You can find it under `examples/bot`.

**Comment by bitwalker** [comment]
@radar Oh, forgot to mention, the reason your app starts and quits immediately is that you probably aren't passing the `--no-halt flag` to mix run. Without that flag, your app will start up, and when the application start callback returns, mix will shut down the app thinking there is nothing else to do. Passing `--no-halt` ensures the VM is left running until it is stopped explicitly (or terminated via CTRL+C, SIGTERM/etc.)

**Comment by radar** [comment]
Thanks @bitwalker. I'll try it out!

**Comment by mrlamroger** [comment]
Thanks @bitwalker !
