### ISSUE TITLE
Handling connection loss [question]

### ISSUE THREAD

**Issue by Hajto** [bitwalker/exirc#53]
I have received such message:
`[info] 'Connection to irc.chat.twitch.tv:6667 closed!'`
How can I restart connection when it's dead?

**Comment by bitwalker** [comment]
A `:disconnected` event is sent to all event handlers, and you can use that to implement your own retry mechanism if so desired. However if a TCP error causes the socket to be closed, then the client will shutdown with `{:tcp_error, error}`, and your supervisor should restart it.
