### ISSUE TITLE
Compile error under 1.3.2?

### ISSUE THREAD

**Issue by shifters67** [bitwalker/exirc#54]
Hi bitwalker,

tried running exirc with elixir 1.3.2 and get the following.  I have added it to a umbrella project and tried to compile it with mix compile and mix deps.compile with same error. 

c:\Users\tom\IdeaProjects\pathweb\apps\pathmaster>mix deps.compile exirc
==> exirc
warning: the dependency :exirc requires Elixir "~> 0.13.1" but you are running on v1.3.2
Compiling 9 files (.ex)

== Compilation error on file lib/exirc/utils.ex ==
*\* (CompileError) lib/exirc/utils.ex:3: cannot import String.from_char_data!/1 because it doesn't exist
    (elixir) src/elixir_import.erl:75: :elixir_import.calculate/6
    (elixir) src/elixir_import.erl:18: :elixir_import.import/4

Am i doing something stupid?

regards

Shifters

**Comment by bitwalker** [comment]
This must be a very old version of `exirc` if it's still got the dependency on `0.13.1`. You'll need to update to the latest version on hex. It currently compiles fine for me on 1.3.x
