### ISSUE TITLE
Starting client as described in examples doesn't link client

### ISSUE THREAD

**Issue by knewter** [bitwalker/exirc#58]
Just thought I'd mention this as it came up :)  I had code that just called `ExIrc.start_client!()` and it worked great until the issue I brought up in #56 came up, at which point the rest of the app was running just fine but the client had died.  Obviously the fix is to explicitly link the client pid that I get back, but I think the examples should point it out or even perhaps a `start_link_client!()` function could be provided / defaulted to.  What are your thoughts?

**Comment by bitwalker** [comment]
Definitely agree, I'll update the examples!
