### ISSUE TITLE
Utils.parse_from/2 regex fails on PDC supported tokens

### ISSUE THREAD

**Issue by heiko-braun** [bitwalker/exirc#59]
`Utils.parse_from/2` fails on PDC supported tokens like this one:

```
nick!~user@pdpc/supporter/professional/user
```

**Comment by bitwalker** [comment]
I'm not familiar with that syntax, what is it supposed to do? I can't find any reference in the IRC message grammar [here](https://tools.ietf.org/html/rfc2812#section-2.3.1), or in the IRCv3 extension specifications. ExIRC doesn't make any attempt to support custom extensions, but if they are part of the protocol, then it is certainly a bug - but as far as I can tell, this is not.

**Comment by heiko-braun** [comment]
If you register your nick with freenode, you'll become a PDC supported and your origin get's cloaked:

```
Who are these people with "pdpc/supporter/" and "pdpc/sponsor/" on the beginnings of their hostnames?
Users who donated to the Peer-Directed Projects Center (PDPC) were given a supporter or sponsor cloak as an acklowledgement and token of our gratitude for their support of the network and the PDPC. The PDPC was subsequently shut down, and so these cloaks are no longer available, although you may still seem them from time to time.
```

See http://freenode-dev.net/faq.shtml#registering

**Comment by heiko-braun** [comment]
But I see that the FAQ acknowledges that `these cloaks are no longer available`, so I guess it's fine to simply ignore (and close) this issue.

**Comment by bitwalker** [comment]
We should probably be supporting cloaks, so I'll keep this open

**Comment by shymega** [comment]
This also occurs on a server I'm on, which has cloaks with two forward-slashes in them. The server uses Inspircd, so it's not a ircd-specific issue. Is there any update on fixing this, by the way? My bot keeps crashing when it encounters a nick with a cloak like that, so it's inhibiting the development of the bot :(

**Comment by vktec** [comment]
The issue seems to be in the regex on line 28 of utils.ex:

```elixir
  @prefix_pattern ~r/^(?<nick>[^!]+)(?:!(?:(?<user>[^@ ]+)@)?(?:(?<host>[\w.:-]+)))?$/
```

Specifically, this section: `(?<host>[\w.:-]+)`
I'd recommend changing that to `(?<host>\S+)`, which captures anything that's not a whitespace character.

As an interesting side note, this syntax in hostnames doesn't appear to be accepted by the standard. However, it is used on a number of IRC networks, so it's a good idea to support it.

**Comment by bitwalker** [comment]
I'll get that PR merged as soon as possible, and push a release once that's done.
