### ISSUE TITLE
Add NickServ support.

### ISSUE THREAD

**Issue by shymega** [bitwalker/exirc#65]
Currently, ExIRC does *not* have NickServ support. Would this be a good idea to add for a future release?

**Comment by bitwalker** [comment]
I'm definitely open to PRs! Unfortunately I'm a little too swamped at the moment to be able to take it on myself.

**Comment by shymega** [comment]
Yo,

Paul Schoenfelder <notifications@github.com> writes:

> I'm definitely open to PRs! Unfortunately I'm a little too swamped
> at the moment to be able to take it on myself.

Completely understandable.

@bitwalker - what do you think of this patch I've made so far? I'm not
really sure how the internals work just yet, so this is the best I've
come up with so far.

https://paste.shymega.org.uk/oohy.ex/elixir#L-1

Specifically, line one. I don't know if I'm parsing it correctly..

-- 
Kind regards,
Dom Rodriguez (shymega/dzr{_,})

"Freedom is the freedom to say two plus two make four.
 If that is granted, all else follows."
	-- George Orwell, Nineteen Eighty-Four.

**Comment by bitwalker** [comment]
That looks correct to me, though your implementation should not swallow all `NOTICE` messages and only send an event for `identify`. I would send `{:notice, message, sender}` in the default case, and `{:identify, message, sender}` when it's an `identify` message.

**Comment by shymega** [comment]
Hello,

Paul Schoenfelder <notifications@github.com> writes:

> That looks correct to me, though your implementation should not
> swallow all `NOTICE` messages and only send an event for `identify`. I
> would send `{:notice, message, sender}` in the default case, and
> `{:identify, message, sender}` when it's an `identify` message.

I'm surprised at myself, to be honest. I don't know much
Elixir/Erlang, but the language has better grown on me than other
languages, so I'm surprised I got this implementation (mostly)
correct.

What do you think of [this][pb] implementation, @bitwalker? I think I
_could_ use cond, but it's not really worth it, but if performance
issues prop up, we can patch that, correct?

Cheers for your reply.

[pb]: https://paste.shymega.org.uk/xysb.txt

-- 
Kind regards,
Dom Rodriguez (shymega/dzr{_,})

"Freedom is the freedom to say two plus two make four.
 If that is granted, all else follows."
	-- George Orwell, Nineteen Eighty-Four.

**Comment by shymega** [comment]
@bitwalker Unfortunately, I lost the code that I put in my last comment! :cry: Will reimplement once college calms down.

**Comment by shymega** [comment]
(Deleted previous comments)

I worked on this patch a bit more, what do you think of this iteration?

Cheers.

[exirc_client_nickserv_patch.txt](https://github.com/bitwalker/exirc/files/1041672/exirc_client_nickserv_patch.txt)

**Comment by bitwalker** [comment]
Sure (also it's easier if you open a PR rather than send a patch, but any contributions are welcome, so no worries if this is easier for you):

1. `String.contains?(...) == true` is redundant, you can just make it `String.contains?(...)` :)
2. Use `if String.contains?(...) do .. else .. end` rather than `cond` here, as there are only two branches.
3. You should remove the `{:noreply, state}` from the `cond` clauses, as it's not used.

**Comment by bitwalker** [comment]
Closing this as #66 was merged :)
