### ISSUE TITLE
running from distillery or exrm releases

### ISSUE THREAD

**Issue by ryanwinchester** [bitwalker/exirc#68]
I can get it running fine using `iex -S mix`.

However, running from a release it just hangs at:

```
10:55:26.911 [debug] Connecting to chat.freenode.net:6697
```

I had to add `:ssl` to my applications in `mix.exs`, but I think there must be more required to get this connecting than that since it is just hanging.

Has anybody got it connecting from a release successfully? What do I need to do?

**Comment by ryanwinchester** [comment]
got it. just needed `:inets` as well

```elixir
extra_applications: [:logger, :ssl, :inets],
```

**Comment by bitwalker** [comment]
I've added the applications list to the `mix.exs` file, so you shouldn't have to do this anymore (at least once I get a new release published to hex)
