### ISSUE TITLE
Code retrieved from mix is different than in the repository.

### ISSUE THREAD

**Issue by teaearlgraycold** [bitwalker/exirc#80]
The following will not work:

```sh
git clone https://github.com/bitwalker/exirc.git
cd exirc/examples/bot
mix deps.get
mix
```

as it results in this error:

```
Compiling 2 files (.ex)

== Compilation error in file lib/bot.ex ==
** (CompileError) lib/bot.ex:74: ExIRC.SenderInfo.__struct__/0 is undefined, cannot expand struct ExIRC.SenderInfo
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
```

This is because the version of the package from mix defines the project module as `ExIrc` and the code in the repository (including the example bot code) refers to the project as `ExIRC`.

**Comment by tchoutri** [comment]
Hi, yup', we're preparing a major release, so you shouldn't consider the master branch as stable, or even working.

You should fallback to the published releases. :)

**Comment by teaearlgraycold** [comment]
>we're preparing a major release

So a 2.0? What kind of changes can I expect?

**Comment by tchoutri** [comment]
@teaearlgraycold New features like support for Whois, Who, better namespacing, and probably fixing odd bugs people might have since forever. :)
