### ISSUE TITLE
Future enhancements

### ISSUE THREAD

**Issue by tchoutri** [bitwalker/exirc#81]
1. We need a simpler way to manage multiple bots per application.
    * We should *not* read the configuration from `config/env.exs` but instead explicitly pass it to the Client process from a supervision tree.
This would enable us to manage multiple bots, on multiple instances.

2. We need a more efficient way to add new bot instances during runtime
     * Use [Dynamic Supervisors](https://hexdocs.pm/elixir/DynamicSupervisor.html#content).

People working on this are:

- @tchoutri (myself)
- @hrefhref

**Comment by rockerBOO** [comment]
Added Dynamic Supervisors in #89
