### ISSUE TITLE
Many compiler warnings with elixir 1.7.4

### ISSUE THREAD

**Issue by shifters67** [bitwalker/exirc#83]
Hi, 

there are many compiler warnings with elixir 1.7.4

warning: found quoted keyword "coveralls" but the quotes are not required. Note that keywords are always atoms, even when quoted, and quotes should only be used to introduce keywords with foreign characters in them

 deps/exirc/mix.exs:11

==> exirc
Compiling 11 files (.ex)
warning: the char_list() type is deprecated, use charlist()
  lib/exirc/utils.ex:16

warning: Integer.to_char_list/1 is deprecated. Use Integer.to_charlist/1 instead
Found at 5 locations:
  lib/exirc/utils.ex:164
  lib/exirc/utils.ex:166
  lib/exirc/utils.ex:168
  lib/exirc/utils.ex:170
  lib/exirc/utils.ex:172

warning: String.strip/1 is deprecated. Use String.trim/1 instead
Found at 4 locations:
  lib/exirc/client.ex:554
  lib/exirc/client.ex:564
  lib/exirc/client.ex:648
  lib/exirc/client.ex:658

warning: String.to_char_list/1 is deprecated. Use String.to_charlist/1 instead
Found at 6 locations:
  lib/exirc/channels.ex:75
  lib/exirc/client.ex:333
  lib/exirc/logger.ex:11
  lib/exirc/logger.ex:19
  lib/exirc/logger.ex:27
  lib/exirc/utils.ex:134

**Comment by tchoutri** [comment]
Thank you very much :)

**Comment by shifters67** [comment]
Hi,

I am still having the same issues - the warnings are still present even after removing the deps and build directories and redownloading.

**Comment by theophile-fl** [comment]
Are you getting ExIRC from Hex or GitHub?

**Comment by tchoutri** [comment]
Are you getting ExIRC from Hex.pm or GitHub?

**Comment by tchoutri** [comment]
Yeah, the package wasn't updated yet. Please use the GitHub master branch until we release a new version on Hex :)

**Comment by shifters67** [comment]
Ah thanks - that fixed them all!

**Comment by tchoutri** [comment]
Fantastic! Thanks for opening the issue :)
