### ISSUE TITLE
Allow usage of "ExIRC.Client.cmd/2" without being logged in

### ISSUE THREAD

**Issue by Simerax** [bitwalker/exirc#88]
Some Servers don't work with `ExIRC.Client.logon/5`. 

In this case it would be beneficial if the client could build its own custom login message via `ExIrc.Client.cmd/2`.
If you try this at the moment the message is immediately discarded with the error `{:error, :not_loged_in}`. 

I think this kind of defeats the purpose of being able to send "raw" commands.

**Comment by tchoutri** [comment]
hi @Simerax
Do you know of the IRCd for which this doesn't work?

**Comment by Simerax** [comment]
Nevermind the subtle problem was in the login process but not the `logon/5` function itself.

**Comment by tchoutri** [comment]
@Simerax Glad you fixed it :) Although I'm still interested how you did it, and with which IRCd, if this is public information you can share.
Cheers!

**Comment by Simerax** [comment]
It was the public twitch IRC-API. I don't know what IRCd they use. https://dev.twitch.tv/docs/irc/guide

They have a few quirks.
* On a successful connection you get multiple messages back which ExIRC sees as `:unrecognized`
* You use OAuth2 or OIDC to authenticate. Therefore your password has to be prefixed with "oauth:"
* When they send you a "PING" they don't want you to answer with "PONG nick" instead with "PONG :tmi.twitch.tv"

I was just a little too quick opening the issue instead of working through those quirks first.
It took me a little while to figure out that you can set ":debug? true" and ":autoping false" in the ExIRC Client.
